INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','9 DE JULIO AGRIDULCES BIZCOCHOS 200G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','9 DE JULIO AZUCARADOS BIZCOCHOS 200G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','9 DE JULIO CLÁSICAS BIZCOCHO 200G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','9 DE JULIO MARMOLADO MINI BUDIN 210G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','9 DE JULIO VAINILLA MINI MADGALENAS 140G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','12','ACEITE CAÑUELAS GIRASOL ','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','ACEITE DE OLIVA EXTRA VIRGEN OLIVA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','ACEITE NATURA 900ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','12','ALICANTE COMINO MOLIDO 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','ALICANTE CONDIMENTO PARA ARROZ 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','ALICANTE CONDIMENTO PARA AVES 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','ALICANTE CONDIMENTO PARA EMPANADAS Y RELLENOS 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','ALICANTE CONDIMENTO PARA PESCADOS 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','ALICANTE CONDIMENTO PARA PIZZA 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','ALICANTE ESPECIAS SURTIDAS MOLIDAS 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','ALICANTE LAUREL TRITURADO 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','ALICANTE ORÉGANO 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','ALICANTE PEREJIL DESHIDRATADO 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','ALICANTE PIMIENTA BLANCA MOLIDA 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','ALICANTE PIMIENTA NEGRA MOLIDA 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','ALICANTE POLLO A LAS FINAS HIERBAS BOLSA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','ALICANTE PROVENZAL AJO Y PEREJIL DESHIDRATADO 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','ALICANTE SABOR EN POLVO CARNE','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','ALICANTE SABOR EN POLVO 4 CUATRO QUESOS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','ALICANTE SABOR EN POLVO PUERRO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','ANANÁS CUMANÁ 567G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','ARVEJAS INALPA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','14','ARVEJAS SAN REMO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','AZUCAR COMUN TIPO A CASTELITA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','27','CACAO EL QUILLA CLÁSICO 200G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','CARBON DE LEÑA DURA ALTA CALORÍA EL TIZON SALTA 3K','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','11','CARBON VEGETAL 5KG','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','CHAMPAGNE CHANDON DELICE','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','CHAMPAGNE SANTA JULIA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','CHANDON DEMI SEC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','CHANDON EXTRA BRUT CHAMPAGNE','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','14','CHEF QUESO RALLADO 100G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','CHIPS DELICIAS DE LA NONNA 400G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','CHOCLO AMARILLO CREMA INALPA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','CHOCLO AMARILLO INALPA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','COMINO AROMAS Y SABORES 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','DULCE DE LECHE LA PAULINA 250G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','EDULCORANTE SI DIET','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','9','FERNET BRANCA MENTA 450CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','FRESITA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','14','GALLETAS CRIOLLITAS ORIGINAL PACK FAMILIAR X3','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','GALLETAS FESTIVA MAX SURTIDAS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','GALLETAS MEDIATARDE CLÁSICAS PACK FAMILIAR X3','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','GALLETAS TODDY CLÁSICAS 150G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','GALLETAS TODDY CLÁSICAS 75G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','GALLETAS TODDY DULCE DE LECHE 150G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','11','GALLETAS TRAVIATA PACK FAMILIAR X3','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','GALLETITAS DIVERSION ','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','GALLETITAS KESBUN PIZZA ESPECIAL DE FUGAZZETA 100G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','HARINA PUREZA ESPECIAL PARA PIZZAS CASERAS 1KG','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','HARINA PUREZA LEUDANTE ULTRA REFINADA 1KG','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','ISAMAY ACEITUNAS VERDES EN SALMUERA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','JARDINERA INALPA 350G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','JBJ PAVITA Y VERDURAS AL ESCABECHE 300G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','22','KNORR CALDO DE GALLINA CAJA CHICA VERDE','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','KNORR SABOR EN SOBRECITOS PROVENZAL','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','KNORR SOPA CREMA VERDURAS 60G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','LECHE DESCREMADA ILOLAY 1LT','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','LECHE ENTERA ILOLAY 1LT','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','23','LENTEJAS SECAS REMOJADAS SAN REMO 350G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','MATE COCIDO TARAGÜÍ TARAGUI 25 SAQUITOS DE 3G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','19','MAYONESA CADADÍA LIVIANA 118G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','8','MAYONESA NATURA 237G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','13','MAYONESA NATURA CHICA 118G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','MERCEIR EXTRA BRUT CHAMPAGNE','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','MORA DURAZNOS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','PASEO CHATITAS 140G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','PATÉ DE FOIE PALADINI','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','PICADILLO DE CARNE PALADINI','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','POLENTA PRESTO PRONTA ARCOR 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','10','POROTOS INCA 202G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','ISAMAY DE TOMATE TRITURADO 950CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','PURÉ DE TOMATE MORA 520G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','8','PURÉ DE TOMATES DE LA HUERTA BAGGIO 210G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','PURÉ DE TOMATES DE LA HUERTA BAGGIO 530G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','QUESO RALLADO LA PAULINA TRADICIONAL 40G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','SAL FINA DOS ANCLAS 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','SALSA LISTA KNOR PIZZA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','SALSA LISTA KNOR POMAROLA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','7','SAVORA ORIGINAL 60G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','11','SIDRA REAL 910ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','SOL MAYOR ROLLOS DE COCINA X3','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','TAHITÍ SALSA DE AJÍ SUAVE 285G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','9','TANG LIMONADA DULCE','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','20','TANG MULTIFRUTA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','TANG NARANJA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','TÉ DE BOLDO LA VIRGINIA 25 SAQUITOS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','TÉ DE MANZANILLA LA VIRGINIA 25 SAQUITOS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','TÉ DE TILO LA VIRGINIA 25 SAQUITOS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','TÉ LA VIRGINIA 25 SAQUITOS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','TOMATE ENTERO PELADO MORA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','TWISTOS HORNEADOS MINITOSTADITAS CUATRO QUESOS 45G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','TWISTOS HORNEADOS MINITOSTADITAS JAMÓN IBÉRICO 45G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VANOLI ACEITUNAS RELLENAS 200G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VANOLI AJÍES EN VINAGRE 130G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','VANOLI LUPINES EN SALMUERA 220G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VANOLI PEPINILLOS EN VINAGRE 200G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VANOLI PICKLES MIXTOS EN VINAGRE 200G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','FIDEOS KNORR CABELLO DE ANGEL 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','FIDEOS JUAN CARLOS COLOMBIA CINTA FINA 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','VINAGRE DE FRTUTA DE MANZANA HALCONES','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','VINO ALMA MORA FINCA LAS MORAS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','VINO COLON MALBEC 2016','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','VINO COLON TORREONTES 2016','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','VINO DADÁ FINCA LAS MORAS VINTAGE 2017','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','VINO DON VALENTIN LACRADO ROBLES CABERNET SAUVIGNON','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','VINO FINCA LAS MORAS CABERNET 2015','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','VINO FINCA LAS MORAS SYRAH','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VINO INTENSO MALBEC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','VINO MALBEC SANTA JULIA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VINO MICHEL TORINO TRADICIONAL','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','12','VINO NORTON 1895 CLÁSICO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','VINO NORTON 1895 CLÁSICO CHICO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','VINO NORTON 1895 CLÁSICO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','VINO SANTA ANA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VINO SANTA ANA CLÁSICO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VINO SANTA JULIA CABERNET SAUVIGNON','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','VINO SANTA JULIA MALBEC ','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','VINO ELEMENTOS TORRONTES','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','8','VINO MICHEL TORINO TINTO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','VINO VALDERROBLES MAGNUN','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VODKA BOLS FRUTILLA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','99','WILDE CALDO DE VERDURAS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','YERBA MATE AGUANTADORA TRADICIONAL 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','YERBA MATE CBSÉ HIERBAS SERRANAS 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','YERBA MATE ROSAMONTE CON PALO 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','16','ALICANTE SABOR EN POLVO VERDURA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','ALICANTE SABOR EN POLVO HONGOS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','ALICANTE SABOR EN POLVO HIERBAS FINAS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','12','ALICANTE SABOR EN POLVO ALBAHACA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','BLEM NARANJA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','FIDEOS JUAN CARLOS COLOMBIA CINTA GRUESA 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','FIDEOS KNORR TIRABUZON 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','FIDEOS KNORR MOSTACHOL 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','FIDEOS KNORR TALLARINES 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','9 DE JULIO MADGALENAS VAINILLA 210G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','9 DE JULIO MADGALENAS VAINILLA CON DULCE DE LECHE 210G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','ADEREZO TIPO MOSTAZA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','ALICANTE CONDIMENTO PARA PREPARAR CHIMICHURRI 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','ALICANTE CONDIMENTO PARA MILANESAS Y SUPREMAS 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','ALICANTE CONDIMENTO AJI TRITURADO 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','ALICANTE CONDIMENTO HIERBAS 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','ALICANTE CONDIMENTO PIMENTON DULCE 25G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','CAFÉ LA VIRGINIA CLASICO EN SOBRES','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','15','CAFÉ LA VIRGINIA CLASICO EN SAQUITOS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','10','ARROZ TRIMACER LARGO FINO 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','7','MERMELADA LA CAMPAGNOLA FRUTILLA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','MERMELADA LA CAMPAGNOLA DURAZNO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','CABALLA LA CAMPAGNOLA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','LAYS CLASICAS 105G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','LAYS QUESO Y CEBOLLA 105G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','DORITOS QUESO 105G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','LAYS JAMON SERRANO 95G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','3D MEGATUBE QUESO 116G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','CHEETOS CLASICOS 116G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','CHEETOS CLASICOS 66G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','3D MEGATUBE QUESO 66G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','DORITOS QUESO 60G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','LAYS CLASICAS 66G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','PEHUAMAR MANI PELADO 90G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','PEP PALITOS 40G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','8','SABOR SPECIAL PARRILLADAS Y ASADO 250G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','7','SABOR SPECIAL CARNES ROJAS Y SALSA 250G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','SABOR SPECIAL POLLOS ARROZ Y PAELLA 250G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','SABOR SPECIAL CERDOS 250G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','SABOR SPECIAL PARRILLADAS Y ASADO 400G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','SABOR SPECIAL CARNES ROJAS Y SALSA 400G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','KESBUN PIZZA ESPECIAL DE JAMON 100G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','KESBUN PIZZA ESPECIAL NAPOLITANA 100G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','KESBUN PIZZA ESPECIAL FUGAZZETA 100G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','TWISTOS SABOR QUESO CREAM 100G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','GALLETITAS ZUCOA CACAO 150G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','GALLETITAS ZUCOA VAINILLA 150G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','CERVEZA QUILMES 1.2 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','11','CERVEZA QUILMES 340CC LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','CERVEZA QUILMES BAJO CERO 1.2 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','7','CERVEZA QUILMES STOUT 1 LITRO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','CERVEZA QUILMES STOUT 473CC LATA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','CERVEZA QUILMES CRISTAL 340CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','11','CERVEZA BRAHMITA 340CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','CERVEZA CORONA 355CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','CERVEZA SKOL 269CC LATA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','CERVEZA STELLA ARTOIS 975CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','7','CERVEZA 1890 1 LITRO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','7','GATORADE MANZANA 500CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','GATORADE FRUTAS TROPICALES 500CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','11','PEPSI 250CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','PEPSI 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','25','PEPSI 500CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','PASO DE LOS TOROS POMELO 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','PEPSI LIGHT 500CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','12','PASO DE LOS TOROS POMELO 500CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','7UP 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','21','7UP 500CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','11','7UP 250CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','AGUA MINERAL ECO DE LOS ANDES 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','20','AGUA MINERAL ECO DE LOS ANDES 500CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','H2OH! CITRUS 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','20','H2OH! CITRUS 500CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','H2OH! NARANCHELO 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','9','H2OH! LIMONETO 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','CERVEZA PATAGONIA 710CC','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','11','COCA COLA 200ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','7','COCA COLA 2.25 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','COCA COLA 500ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','9','COCA COLA 354ML LATA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','COCA COLA SIN AZUCAR 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','COCA COLA SIN AZUCAR 500ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','9','COCA COLA 1 LITRO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','SPRITE 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','8','SPRITE 354ML LATA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','8','SPRITE 200ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','SPRITE 2.25 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','FANTA 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','15','FANTA 500ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','8','FANTA 354ML LATA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','9','SCHWEPPES POMELO 354ML LATA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','7','SCHWEPPES POMELO 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','SCHWEPPES POMELO ZERO 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','AGUA MINERAL BONAQUA 500ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','AGUA MINERAL BONAQUA 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','AGUA MINERAL BONAQUA 2.25 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','AQUARIUS NARANJA 500ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','POWERADE MOUNTAIN BLAST 500ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','POWERADE MANZANA 500ML','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','CEPITA DEL VALLE MULTIFRUTA 1 LITRO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','CEPITA DEL VALLE NARANJA 1 LITRO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','CEPITA DEL VALLE DURAZNO 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','CEPITA DEL VALLE NARANJA 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','AQUARIUS POMELO 1.5 LITROS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','SABOR SPECIAL CHIMICHURRI TIPO CRIOLLO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','GALLETITAS SERRANAS X3','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','18','JABON EN POLVO DRIVE HORTENSIAS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','13','JABON EN POLVO DRIVE ROSAS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','JABON ESPADOL','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','JABON VERITAS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','8','KNORR CALDO SABOR 4 QUESOS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','3','MYHOGAR ROLLO PAPEL X2','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','LENTEJAS INALPA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','KNORR PURE DE PAPAS','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','KETCHUP CADADIA 250G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','SALSA GOLF CADADIA250G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','10','KNORR CALDO AZAFRAN Y TOMILLO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','18','KNORR CALDO DE VERDURA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','18','KNORR CALDO DE GALLINA AMARILLO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','KNORR CALDO MOSTAZA Y VINO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','POROTOS GUARDIA VIEJA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','9','TANG DURAZNO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','21','TANG NARANJA MANGO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','SAL FINA CELUSAL 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','VANOLI CEBOLLITAS EN VINAGRE 220G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','21','VELAS MSI','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','VINAGRE DE ALCOHOL HALCONERO','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','VINO VALMONT','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','5','VINO VALDERROBLES VARIETALES','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','VINO SANTA JULIA 2013','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','VODKA NIKOV','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','7','YERBA MATE SINCERIDAD 500G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','1','CHAMPAGNE MERCIER EXTRA BRUT','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','CHAMPAGNE CHANDON BRUT NATURE','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','2','BOLSA DE LEÑA','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','11','SAVORA ORIGINAL 250G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','TWISTOS HORNEADOS MINITOSTADITAS CUATRO QUESOS 112G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','4','TWISTOS HORNEADOS MINITOSTADITAS JAMÓN IBÉRICO 112G','1');
INSERT INTO producto (id_producto_tipo,cantidad,descripcion_breve,usuario) values('4','6','VINO INTENSO CABERNET SAUVIGNON','1');
