-- insert de productos , con random en precio y cantidad
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11750','56.72','153.84','TRIPA','TRIPA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11760','87.59','45.52','CHINCHULÍN','CHINCHULÍN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11770','129.74','136.71','RIÑON','RIÑON','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11780','75.59','51.67','CORAZÓN','CORAZÓN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11790','91.61','63.52','ENTRAÑA','ENTRAÑA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11800','112.70','30.25','RABO','RABO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11810','111.02','67.27','MONDONGO','MONDONGO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11820','26.48','105.01','HÍGADO','HÍGADO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11830','147.85','145.47','MOLLEJAS','MOLLEJAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11850','124.76','41.16','LENGUA','LENGUA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11860','147.95','60.91','QUIJADA','QUIJADA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11870','111.75','66.32','DUOS','DUOS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11880','76.25','56.87','CARRE ','CARRE ','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11890','64.16','30.64','PECHITO','PECHITO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11900','57.16','138.59','JAMON ENTERO','JAMON ENTERO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11910','143.55','80.19','CHURRASQUITO','CHURRASQUITO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11920','153.14','153.24','PALETA ENTERA','PALETA ENTERA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11930','82.18','74.79','PAPADA','PAPADA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11940','103.81','103.02','TOCINO','TOCINO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11950','116.78','54.89','MATAMBRITOS','MATAMBRITOS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('2','11960','114.8','53.97','BONDIOLA','BONDIOLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'97.23','52.99','1/2 RESES','1/2 RESES','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'47.83','139.70','1/4 RUEDA','1/4 RUEDA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'59.85','111.79','1/4 PISTOLA','1/4 PISTOLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'73.83','141.13',' 1/4 DELANTERO ',' 1/4 DELANTERO ','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'103.91','82.96','BARRAS','BARRAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'130.53','147.28','MOCHITOS','MOCHITOS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'134.40','121.54','MANTAS','MANTAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'106.05','71.28','RECORTE','RECORTE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'56.56','120.85','PARRILLERO','PARRILLERO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'98.58','47.91','JUEGOS DE ACHURAS','JUEGOS DE ACHURAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'85.37','33.54','RECORTE DE 1','RECORTE DE 1','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('3',NULL,'49.46','32.77','RECORTE DE 2°','RECORTE DE 2°','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','10990','48.95','98.46','CHORIZO ESPECIAL','CHORIZO ESPECIAL','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11000','53.33','121.42','CHORIZO PARRILLERO','CHORIZO PARRILLERO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11010','125.56','31.82','CHORIZO DE CERDO','CHORIZO DE CERDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11020','31.58','152.98','CHORIZO COLORADO','CHORIZO COLORADO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11030','41.82','105.86','SALCHICHA PARRILL.','SALCHICHA PARRILL.','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11040','144.40','74.99','MORCILLA','MORCILLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11050','72.38','32.30','MORCILLA','MORCILLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11060','54.58','67.80','SALCHICHAS SNACK','SALCHICHAS SNACK','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11070','38.68','32.12','PATE','PATE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11080','107.30','128.84','QUESO DE CERDO','QUESO DE CERDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11100','30.12','40.97','PICADA COMUN','PICADA COMUN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11110','116.23','71.09','PICADA INTERMEDIA','PICADA INTERMEDIA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11120','93.91','58.71','PICADA ESPECIAL','PICADA ESPECIAL','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11130','37.92','62.85','PUCHERO COMUN','PUCHERO COMUN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11140','39.26','75.03','PUCHERO ESPECIAL','PUCHERO ESPECIAL','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11150','41.23','136.25','CANINO','CANINO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11160','92.22','120.08','MATAMBRE','MATAMBRE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11170','111.71','111.06','VACIO','VACIO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11180','106.86','150.04','ALA DE PECHO','ALA DE PECHO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11190','133.86','45.14','COSTILLA','COSTILLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11200','30.18','81.05','MARUCHA','MARUCHA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11210','112.81','61.14','TAPA DE NALGA','TAPA DE NALGA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11220','47.51','86.23','CORTE MALVINA','CORTE MALVINA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11230','39.46','109.62','FALDA','FALDA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11240','136.62','122.41','COSTELETAS','COSTELETAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11250','105.71','58.51','AGUJA','AGUJA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11260','57.70','60.64','BRAZUELO','BRAZUELO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11270','36.16','140.54','BIFE ANCHO/ANGOSTO','BIFE ANCHO/ANGOSTO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11280','114.39','106.96','ENTRECOT','ENTRECOT','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11290','87.57','83.18','ROAST BEEF','ROAST BEEF','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11300','114.24','125.60','NALGAS','NALGAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11310','43.25','119.60','LOMO','LOMO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11320','36.66','136.16','PECETO','PECETO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11330','61.65','43.97','CUADRIL','CUADRIL','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11340','123.51','80.34','PALOMITA','PALOMITA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11350','130.63','74.57','JAMON CUADRADO','JAMON CUADRADO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11360','46.80','60.01','CABEZA DE LOMO','CABEZA DE LOMO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11370','108.51','127.80','PULPA BRAZUELO','PULPA BRAZUELO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11380','149.57','143.06','PULPA PALETA','PULPA PALETA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11390','25.88','88.76','TORTUGUITA','TORTUGUITA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11400','142.61','74.57','MILANESAS DE CARNE','MILANESAS DE CARNE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11410','55.91','69.85','MILANESAS DE POLLO','MILANESAS DE POLLO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11420','63.67','56.89','HAMBURGUESAS','HAMBURGUESAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11430','38.15','62.15','ALBONDIGAS','ALBONDIGAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11440','125.67','141.31','COSTELETAS','COSTELETAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11450','138.76','58.50','BONDIOLA','BONDIOLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11460','83.87','56.01','MATAMBRITO','MATAMBRITO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11470','69.46','84.68','COSTILLA/PECHITO','COSTILLA/PECHITO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11480','28.95','31.49','PULPAS','PULPAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11490','37.08','103.86','MARUCHA','MARUCHA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11500','141.58','93.29','CARACU','CARACU','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11510','69.25','70.19','PAT./HUE./CUE.','PATITA/HUESITO/CUERITO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11520','79.81','84.03','MILANESAS','MILANESAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11530','77.84','49.35','HAMBURGUESAS','HAMBURGUESAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11540','78.48','103.88','PATAMUSLO','PATAMUSLO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11550','122.90','93.31','TROZADO','TROZADO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11560','89.56','151.96','PECHUGA','PECHUGA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11570','41.96','57.83','FILET','FILET','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11580','135.13','122.31','BROCHET','BROCHET','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11590','130.99','45.09','BONDIOLA','BONDIOLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11600','108.72','34.35','PALETA','PALETA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11610','61.44','49.20','JAMON COCIDO','JAMON COCIDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11620','110.73','46.97','JAMON CRUDO','JAMON CRUDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11630','102.46','41.46','SALAME MILAN','SALAME MILAN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11640','34.33','129.92','SALAMIN','SALAMIN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11650','117.64','59.77','QUESO BARRA','QUESO BARRA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11660','61.96','134.76','CREMOSO','CREMOSO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11670','129.93','111.41','CASCARA COLORADA','CASCARA COLORADA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11680','53.51','144.59','QUESO CRE','QUESO CRE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11690','51.58','88.59','QUESO TREEMBLAY','QUESO TREEMBLAY','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11700','54.32','132.61','QUESO PROVOLETA','QUESO PROVOLETA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11710','126.28','116.29','QUESO SARDO','QUESO SARDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11720','78.64','33.00','MORTADELA','MORTADELA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, precio, cantidad, descripcion_breve, descripcion_larga, usuario, fecha_baja) VALUES ('1','11730','122.70','144.23','MORTADELA','MORTADELA','1',NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','9 de julio agridulces bizcochos 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','9 de julio azucarados bizcochos 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','9 de julio clásicas bizcocho 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','40','9 de julio marmolado mini budin 210g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','9 de julio vainilla mini madgalenas 140g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Aceite Cañuelas Girasol ', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','100','Aceite de oliva extra virgen Oliva', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','45','Aceite Natura 900ml', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','14','Alicante Comino molido 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','13.5','Alicante condimento para arroz 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Alicante Condimento para aves 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Alicante Condimento para empanadas y rellenos 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','16','Alicante Condimento para pescados 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Alicante condimento para pizza 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Alicante especias surtidas molidas 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Alicante Laurel triturado 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Alicante orégano 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Alicante Perejil deshidratado 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','Alicante pimienta blanca molida 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','22','Alicante pimienta negra molida 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','28','Alicante pollo a las finas hierbas bolsa', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Alicante Provenzal ajo y perejil deshidratado 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Alicante sabor en polvo', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Alicante sabor en polvo 4 cuatro quesos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Alicante sabor en polvo puerro', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','55','Ananás umaná 567g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Arvejas Inalpa', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Arvejas San Remo', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','Azucar comun tipo A Castelita', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Cacao el Quilla clásico 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Carbon de leña dura alta caloría El Tizon Salta 3kg', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Carbon vegetal 5kg', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','260','Champagne Chandon Delice', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Champagne Santa Julia', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','192','Chandon demi sec', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Chandon extra brut champagne', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Chef queso rallado 100g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','33','Chips Delicias de la Nonna 400g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','23','Choclo amarillo Crema Inalpa', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','Choclo amarillo Inalpa', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Comino Aromas y sabores 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Dulce de leche La paulina 250g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Edulcorante Si diet', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','130','Fernet Branca menta', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','96','Fresita', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','29','galletas criollitas original pack familiar x3', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Galletas Festiva max surtidas', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','galletas mediatarde clásicas pack familiar x3', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','Galletas Toddy clásicas 150g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Galletas Toddy clásicas 75g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','Galletas Toddy dulce de leche 150g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','35','galletas traviata pack familiar x3', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','galletitas diversion ', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Galletitas Kesbun pizza especial de fugazzeta 100g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','32','Harina Pureza Especial para pizzas caseras 1kg', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','23','Harina Pureza Leudante ultra refinada 1kg', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Isamay aceitunas verdes en salmuera', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','17','Jardinera Inalpa 350g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','120','JBJ Pavita y verduras al escabeche 300g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Knorr caldo de gallina caja chica', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Knorr sabor en sobrecitos Provenzal', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Knorr sopa crema Verduras 60g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','32','Leche descremada Ilolay 1lt', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','32','Leche entera Ilolay 1lt', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Lentejas Secas remojadas San Remo 350g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','22','mate cocido taragüí taragui 25 saquitos de 3g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Mayonesa CadaDía liviana 118g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','Mayonesa Natura 237g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','Mayonesa Natura chica 118g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Merceir extra brut champagne', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','42','Mora duraznos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','paseo chatitas 140g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Paté de foie Paladini', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Picadillo de carne Paladini', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','19.5','polenta presto pronta arcor 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','23','Porotos Inca 202g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','42','Producto de tomate triturado', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','13','Puré de tomate Mora 520g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','Puré de tomates De la Huerta Baggio 210g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','Puré de tomates De la Huerta Baggio 530g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Queso rallado La paulina tradicional', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Sal fina Dos anclas 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Salsa lista Knor pizza', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Salsa lista Knor pomarola', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Savora original 60g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Sidra Real 910ml', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','Sol mayor rollos de cocina x3', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Tahití salsa de ají suave 285g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Tang limonada dulce', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Tang multifruta', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Tang naranja', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','té de boldo La virginia 25 saquitos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','28','té de manzanilla La virginia 25 saquitos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','té de tilo La virginia 25 saquitos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','té La virginia 25 saquitos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Tomate entero pelado Mora', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','40','Twistos horneados minitostaditas cuatro quesos 45g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','40','Twistos horneados minitostaditas jamón ibérico 45g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','38','Vanoli aceitunas rellenas 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','48','Vanoli Ajíes en vinagre 130g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','39','Vanoli lupines en salmuera 220g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','43','Vanoli pepinillos en vinagre 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','37','Vanoli pickles mixtos en vinagre 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','video cabello de angel knorr 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','47','videos secos juan carlos columba 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','17','Vinagre de frtuta de manzana Halcones', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','145','Vino Alma Mora Finca Las moras', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino Colon Malbec 2016', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','95','Vino Colon torreontes 2016', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','125','Vino Dadá Finca Las moras Vintage 2017', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino Don Valentin lacrado roble Cabernet Sauvignon 2015', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino Finca Las moras Cabernet 2015', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','115','Vino Finca Las moras syrah', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','90','Vino Intenso Malbec', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','140','Vino Malbec Santa Julia', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino Michel Torino', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','50','Vino Norton 1895 Clásico', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','85','Vino Norton 1895 Clásico', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','98','Vino Norton 1895 Clásico', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','45','Vino Santa Ana', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','75','Vino Santa Ana Clásico', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','105','Vino Santa Julia Cabernet Sauvignon', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','105','Vino Santa Julia Malbec ', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino tinto Elementos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','53','Vino tinto Michel Torino', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','91','Vino Valderrobles Magnun', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vodka Bols Frutilla', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Wilde caldo de verduras', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','45','yerba mate Aguantadora tradicional 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','37','yerba mate CBSé hierbas serranas 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','43','yerba mate Rosamonte con palo 500g', '1', NULL);


