-- insert de productos , con random en precio y cantidad
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11750','TRIPA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11760','CHINCHULÍN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11770','RIÑON','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11780','CORAZÓN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11790','ENTRAÑA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11800','RABO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11810','MONDONGO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11820','HÍGADO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11830','MOLLEJAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11850','LENGUA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11860','QUIJADA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11870','DUOS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11880','CARRE ','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11890','PECHITO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11900','JAMON ENTERO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11910','CHURRASQUITO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11920','PALETA ENTERA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11930','PAPADA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11940','TOCINO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11950','MATAMBRITOS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('2','11960','BONDIOLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'1/2 RESES','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'1/4 RUEDA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'1/4 PISTOLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,' 1/4 DELANTERO ','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'BARRAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'MOCHITOS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'MANTAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'RECORTE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'PARRILLERO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'JUEGOS DE ACHURAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'RECORTE DE 1','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('3',NULL,'RECORTE DE 2°','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','10990','CHORIZO ESPECIAL','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11000','CHORIZO PARRILLERO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11010','CHORIZO DE CERDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11020','CHORIZO COLORADO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11030','SALCHICHA PARRILL.','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11040','MORCILLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11050','MORCILLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11060','SALCHICHAS SNACK','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11070','PATE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11080','QUESO DE CERDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11100','PICADA COMUN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11110','PICADA INTERMEDIA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11120','PICADA ESPECIAL','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11130','PUCHERO COMUN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11140','PUCHERO ESPECIAL','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11150','CANINO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11160','MATAMBRE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11170','VACIO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11180','ALA DE PECHO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11190','COSTILLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11200','MARUCHA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11210','TAPA DE NALGA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11220','CORTE MALVINA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11230','FALDA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11240','COSTELETAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11250','AGUJA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11260','BRAZUELO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11270','BIFE ANCHO/ANGOSTO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11280','ENTRECOT','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11290','ROAST BEEF','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11300','NALGAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11310','LOMO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11320','PECETO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11330','CUADRIL','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11340','PALOMITA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11350','JAMON CUADRADO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11360','CABEZA DE LOMO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11370','PULPA BRAZUELO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11380','PULPA PALETA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11390','TORTUGUITA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11400','MILANESAS DE CARNE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11410','MILANESAS DE POLLO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11420','HAMBURGUESAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11430','ALBONDIGAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11440','COSTELETAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11450','BONDIOLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11460','MATAMBRITO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11470','COSTILLA/PECHITO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11480','PULPAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11490','MARUCHA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11500','CARACU','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11510','PAT./HUE./CUE.','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11520','MILANESAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11530','HAMBURGUESAS','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11540','PATAMUSLO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11550','TROZADO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11560','PECHUGA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11570','FILET','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11580','BROCHET','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11590','BONDIOLA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11600','PALETA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11610','JAMON COCIDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11620','JAMON CRUDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11630','SALAME MILAN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11640','SALAMIN','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11650','QUESO BARRA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11660','CREMOSO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11670','CASCARA COLORADA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11680','QUESO CRE','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11690','QUESO TREEMBLAY','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11700','QUESO PROVOLETA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11710','QUESO SARDO','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11720','MORTADELA','1',NULL);
INSERT INTO producto (id_producto_tipo, id_codigo_barra, descripcion_breve,  usuario, fecha_baja) VALUES ('1','11730','MORTADELA','1',NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','9 de julio agridulces bizcochos 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','9 de julio azucarados bizcochos 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','9 de julio clásicas bizcocho 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','40','9 de julio marmolado mini budin 210g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','9 de julio vainilla mini madgalenas 140g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Aceite Cañuelas Girasol ', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','100','Aceite de oliva extra virgen Oliva', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','45','Aceite Natura 900ml', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','14','Alicante Comino molido 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','13.5','Alicante condimento para arroz 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Alicante Condimento para aves 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Alicante Condimento para empanadas y rellenos 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','16','Alicante Condimento para pescados 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Alicante condimento para pizza 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Alicante especias surtidas molidas 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Alicante Laurel triturado 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Alicante orégano 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Alicante Perejil deshidratado 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','Alicante pimienta blanca molida 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','22','Alicante pimienta negra molida 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','28','Alicante pollo a las finas hierbas bolsa', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Alicante Provenzal ajo y perejil deshidratado 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Alicante sabor en polvo', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Alicante sabor en polvo 4 cuatro quesos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Alicante sabor en polvo puerro', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','55','Ananás umaná 567g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Arvejas Inalpa', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Arvejas San Remo', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','Azucar comun tipo A Castelita', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Cacao el Quilla clásico 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Carbon de leña dura alta caloría El Tizon Salta 3kg', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Carbon vegetal 5kg', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','260','Champagne Chandon Delice', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Champagne Santa Julia', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','192','Chandon demi sec', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Chandon extra brut champagne', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Chef queso rallado 100g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','33','Chips Delicias de la Nonna 400g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','23','Choclo amarillo Crema Inalpa', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','Choclo amarillo Inalpa', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Comino Aromas y sabores 25g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Dulce de leche La paulina 250g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Edulcorante Si diet', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','130','Fernet Branca menta', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','96','Fresita', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','29','galletas criollitas original pack familiar x3', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Galletas Festiva max surtidas', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','galletas mediatarde clásicas pack familiar x3', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','Galletas Toddy clásicas 150g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Galletas Toddy clásicas 75g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','Galletas Toddy dulce de leche 150g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','35','galletas traviata pack familiar x3', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','galletitas diversion ', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Galletitas Kesbun pizza especial de fugazzeta 100g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','32','Harina Pureza Especial para pizzas caseras 1kg', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','23','Harina Pureza Leudante ultra refinada 1kg', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Isamay aceitunas verdes en salmuera', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','17','Jardinera Inalpa 350g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','120','JBJ Pavita y verduras al escabeche 300g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Knorr caldo de gallina caja chica', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Knorr sabor en sobrecitos Provenzal', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Knorr sopa crema Verduras 60g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','32','Leche descremada Ilolay 1lt', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','32','Leche entera Ilolay 1lt', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Lentejas Secas remojadas San Remo 350g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','22','mate cocido taragüí taragui 25 saquitos de 3g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Mayonesa CadaDía liviana 118g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','30','Mayonesa Natura 237g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','Mayonesa Natura chica 118g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Merceir extra brut champagne', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','42','Mora duraznos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','paseo chatitas 140g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Paté de foie Paladini', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Picadillo de carne Paladini', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','19.5','polenta presto pronta arcor 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','23','Porotos Inca 202g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','42','Producto de tomate triturado', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','13','Puré de tomate Mora 520g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','15','Puré de tomates De la Huerta Baggio 210g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','Puré de tomates De la Huerta Baggio 530g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Queso rallado La paulina tradicional', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','Sal fina Dos anclas 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Salsa lista Knor pizza', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','26','Salsa lista Knor pomarola', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','12','Savora original 60g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Sidra Real 910ml', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','25','Sol mayor rollos de cocina x3', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Tahití salsa de ají suave 285g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Tang limonada dulce', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Tang multifruta', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Tang naranja', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','té de boldo La virginia 25 saquitos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','28','té de manzanilla La virginia 25 saquitos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','té de tilo La virginia 25 saquitos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','té La virginia 25 saquitos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','18','Tomate entero pelado Mora', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','40','Twistos horneados minitostaditas cuatro quesos 45g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','40','Twistos horneados minitostaditas jamón ibérico 45g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','38','Vanoli aceitunas rellenas 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','48','Vanoli Ajíes en vinagre 130g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','39','Vanoli lupines en salmuera 220g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','43','Vanoli pepinillos en vinagre 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','37','Vanoli pickles mixtos en vinagre 200g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','20','video cabello de angel knorr 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','47','videos secos juan carlos columba 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','17','Vinagre de frtuta de manzana Halcones', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','145','Vino Alma Mora Finca Las moras', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino Colon Malbec 2016', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','95','Vino Colon torreontes 2016', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','125','Vino Dadá Finca Las moras Vintage 2017', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino Don Valentin lacrado roble Cabernet Sauvignon 2015', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino Finca Las moras Cabernet 2015', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','115','Vino Finca Las moras syrah', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','90','Vino Intenso Malbec', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','140','Vino Malbec Santa Julia', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino Michel Torino', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','50','Vino Norton 1895 Clásico', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','85','Vino Norton 1895 Clásico', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','98','Vino Norton 1895 Clásico', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','45','Vino Santa Ana', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','75','Vino Santa Ana Clásico', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','105','Vino Santa Julia Cabernet Sauvignon', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','105','Vino Santa Julia Malbec ', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vino tinto Elementos', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','53','Vino tinto Michel Torino', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','91','Vino Valderrobles Magnun', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','1','Vodka Bols Frutilla', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','8','Wilde caldo de verduras', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','45','yerba mate Aguantadora tradicional 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','37','yerba mate CBSé hierbas serranas 500g', '1', NULL);
INSERT INTO producto (id_producto_tipo, precio,descripcion_breve,usuario, fecha_baja) VALUES ('4','43','yerba mate Rosamonte con palo 500g', '1', NULL);


