INSERT INTO `vistasaldoclientetodos` VALUES (1, 'ZR', 'JUAN CARLOS MARECO', 78243);
INSERT INTO `vistasaldoclientetodos` VALUES (2, 'MR', 'MR.ZANUTIGH MARIANO GERMAN', -0);
INSERT INTO `vistasaldoclientetodos` VALUES (3, 'N', 'N.GUTIERREZ NERINA GUADALUPE', 19702);
INSERT INTO `vistasaldoclientetodos` VALUES (15, 'JJ', 'JUANJO', 1138);
INSERT INTO `vistasaldoclientetodos` VALUES (16, 'GT', 'LA TROPA', 9169);
INSERT INTO `vistasaldoclientetodos` VALUES (19, 'JP', 'JP.JORGE PORTILLO', 540);
INSERT INTO `vistasaldoclientetodos` VALUES (20, 'L', 'L.HÉCTOR OJEDA', 4442.1);
INSERT INTO `vistasaldoclientetodos` VALUES (21, 'N2', 'N2', 11726);
INSERT INTO `vistasaldoclientetodos` VALUES (22, 'TM', 'TATY.RAMÓN MIRANDA', -0);
INSERT INTO `vistasaldoclientetodos` VALUES (23, 'RS', 'RS.LORENA SILVETTI', -0);
INSERT INTO `vistasaldoclientetodos` VALUES (24, 'BS', 'BS.JULIO BURRELLA', -0);
INSERT INTO `vistasaldoclientetodos` VALUES (25, 'Z', 'Z.EDUARDO', -0);
INSERT INTO `vistasaldoclientetodos` VALUES (26, 'MX', 'MX.MAXIMILIANO ALBORNOZ', 34945);
INSERT INTO `vistasaldoclientetodos` VALUES (27, 'AF', 'AF.CARNICERÍA LA MEJOR', 305241);
INSERT INTO `vistasaldoclientetodos` VALUES (28, 'D', 'D.DIEGO COLMÁN', 48649);
INSERT INTO `vistasaldoclientetodos` VALUES (29, 'DM', 'DM.DAMIAN', -0);
INSERT INTO `vistasaldoclientetodos` VALUES (30, 'CA', 'CA.CACHO GAITAN', 18720);
INSERT INTO `vistasaldoclientetodos` VALUES (31, 'R', 'R.HUGO PAIVA', 43866.5);
INSERT INTO `vistasaldoclientetodos` VALUES (32, 'JM', 'JOSÉ MAIDANA', 13309.349999999999);
INSERT INTO `vistasaldoclientetodos` VALUES (33, 'AL', 'AL.MANUEL LÓPEZ', 21970);
INSERT INTO `vistasaldoclientetodos` VALUES (34, 'LP 3', 'LP3.SUPER CHINO', 11852.8);
INSERT INTO `vistasaldoclientetodos` VALUES (35, 'LP 2', 'LÓPEZ CRISTÍAN', 20520);
INSERT INTO `vistasaldoclientetodos` VALUES (36, 'LG', 'LUIS GONZLÉZ', 18777);
INSERT INTO `vistasaldoclientetodos` VALUES (37, 'NK', 'NK.NICOLÁS', 21919);
INSERT INTO `vistasaldoclientetodos` VALUES (38, 'DA 1', ' DA 1 IVÁN', 4651.199999999997);
INSERT INTO `vistasaldoclientetodos` VALUES (39, 'L 5', 'L5.FERNANDO \"EL TORO NEGRO\"', 15573);
INSERT INTO `vistasaldoclientetodos` VALUES (41, 'N 3', 'N3.MANUEL', 21970);
INSERT INTO `vistasaldoclientetodos` VALUES (43, 'JU', 'JU.JULIO CONTE', 31399);
INSERT INTO `vistasaldoclientetodos` VALUES (44, 'LP 4', 'LP 4', 7456);
INSERT INTO `vistasaldoclientetodos` VALUES (45, 'ED', 'ED.EDUARDO', 205.2);
INSERT INTO `vistasaldoclientetodos` VALUES (46, 'PYC', 'MARIO PAN Y CALI', 3230);
INSERT INTO `vistasaldoclientetodos` VALUES (47, 'ZR', 'ZR.JUAN CARLOS MARECO', 57243);
INSERT INTO `vistasaldoclientetodos` VALUES (48, 'AD', 'AD. CARLOS', 21133.800000000003);
INSERT INTO `vistasaldoclientetodos` VALUES (49, 'S', 'SILVIA ACOSTA', 8360);
INSERT INTO `vistasaldoclientetodos` VALUES (54, '63. ', 'LEONARDO HIJO DE PININO', 7248);
INSERT INTO `vistasaldoclientetodos` VALUES (58, 'J2', 'JUAN 2', 51.55);
